name: Renovate
on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '11 13 * * *'
  pull_request:

jobs:
  renovate:
    env:
      RENOVATE_LOG_LEVEL: ${{ vars.LOG_LEVEL }}
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v3
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@316d7cd859606d6039a2182b7d69199e9b036835 # v46.2.1
        with:
          configurationFile: config.js
          token: '${{ steps.get_token.outputs.token }}'
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL)$"
        env:
          RENOVATE_DRY_RUN: ${{ github.event_name == 'pull_request' && 'full' || '' }}
